name: flower_store
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.2
  http: ^1.2.1
  json_annotation: ^4.9.0
  dio: ^5.5.0+1
  mailer: ^6.1.2
  fluttertoast: ^8.2.6




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^10.0.1
  control_style: ^0.1.0
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  curved_navigation_bar: ^1.0.6
  intl: ^0.19.0
  date_picker_plus: ^3.0.2
  
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  dropdown_button2: ^2.3.9
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  
flutter:
  fonts:
  - family: CustomIcon
    fonts:
    - asset: assets/fonts/CustomIcon.ttf
    
  - family: Roboto
    fonts:
    - asset: assets/fonts/Roboto-Medium.ttf

  - family: Inter
    fonts:
      - asset: assets/fonts/Inter-Medium.ttf

  - family: Rubik
    fonts:
      - asset: assets/fonts/Rubik-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vectors/setting.svg
    - assets/fonts/Rubik-Medium.ttf
    - assets/images/
    - assets/icons/back_icon.svg
    - assets/fonts/Inter-Medium.ttf
